name: Terraform Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Terraform Release Action
        uses: KarthikKunchala23/gp-github-actions/terraform-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}